name: "Run QA Assistant"
description: "Custom action using a private DockerHub image"

inputs:
  key:
    description: 'model key access'
    required: true
  input-file:
    description: 'path to input file'
    required: true
    default: 'pom.xml'
  output-file:
    description: 'path to output file'
    required: true
    default: 'qa.json'

runs:
  using: "docker"
  image: "docker://jacobsonius/qa-assistant:latest"
  args:
    - ${{ inputs.key }}
    - ${{ inputs.input-file }}
    - ${{ inputs.output-file }}