name: "Run QA Assistant"
description: "Custom action using a private DockerHub image"

inputs:
  key:
    description: 'model access key'
    required: true
  action-name:
    description: 'qa action'
    required: true
    default: 'INDEX' # INDEX/PLAN/JUNIT
  target-value:
    description: 'Target value in percent'
    required: false
    default: '80'
  test-report-dir:
    description: 'path to report files'
    required: false
    default: './target/surefire-reports/*.xml'
  coverage-report-dir:
    description: 'path to report files'
    required: false
    default: './target/site/jacoco/index.html'
  input-dir:
    description: 'path to input files'
    required: true
    default: './'
  output-dir:
    description: 'path to output files'
    required: true
    default: './'

runs:
  using: "docker"
  image: "docker://jacobsonius/qa-assistant:latest"
  args:
    - ${{ inputs.key }}
    - ${{ inputs.action-name }}
    - ${{ inputs.target-value }}
    - ${{ inputs.test-report-dir }}
    - ${{ inputs.coverage-report-dir }}
    - ${{ inputs.input-dir }}
    - ${{ inputs.output-dir }}