name: "QA Assistant Action"
description: "QA Assistant Action for GitHub CI/CD"

inputs:
  key:
    description: 'Qwen model access key'
    required: true
  action-name:
    description: 'QA Assistant action name'
    required: true
    default: 'INDEX' # INDEX/PLAN/JUNIT_UPDATE
  target-value:
    description: 'Target value in percent'
    required: false
    default: '0.8'
  attempt:
    description: 'Step of processing'
    required: false
    default: '0'
  artefacts-dir:
    description: 'Path to artefact files'
    required: true
    default: './qa-artefacts'
  build-report-dir:
    description: 'Path to build log file'
    required: false
    default: '.'
  test-report-dir:
    description: 'Path to test report files'
    required: false
    default: './target/surefire-reports'
  coverage-report-dir:
    description: 'Path to coverage report files'
    required: false
    default: './target/site/jacoco'
  input-dir:
    description: 'Path to source files'
    required: true
    default: '.'
  output-dir:
    description: 'Path to output files'
    required: true
    default: '.'

runs:
  using: "docker"
  image: "docker://jacobsonius/qa-assistant:latest"
  args:
    - ${{ inputs.key }}
    - ${{ inputs.action-name }}
    - ${{ inputs.target-value }}
    - ${{ inputs.attempt }}
    - ${{ inputs.artefacts-dir }}
    - ${{ inputs.build-report-dir }}
    - ${{ inputs.test-report-dir }}
    - ${{ inputs.coverage-report-dir }}
    - ${{ inputs.input-dir }}
    - ${{ inputs.output-dir }}