name: "Run QA Assistant"
description: "Custom action using a private DockerHub image"

inputs:
  key:
    description: 'model key access'
    required: true
  action-name:
    description: 'qa action'
    required: true
    default: 'INDEX'
  input-dir:
    description: 'path to input files'
    required: true
    default: './'
  output-fir:
    description: 'path to output files'
    required: true
    default: './'

runs:
  using: "docker"
  image: "docker://jacobsonius/qa-assistant:latest"
  args:
    - ${{ inputs.key }}
    - ${{ inputs.action }}
    - ${{ inputs.input-dir }}
    - ${{ inputs.output-dir }}