name: "QA Assistant Action"
description: "QA Assistant Action for GitHub CI/CD"

inputs:
  docker-username:
    description: 'Docker Hub username'
    required: true
  docker-password:
    description: 'Docker Hub password'
    required: true
  key:
    description: 'Qwen model access key'
    required: true
  action-name:
    description: 'QA Assistant action name'
    required: true
    default: 'INDEX' # INDEX/PLAN/JUNIT/JUNIT_UPDATE
  target-value:
    description: 'Target value in percent'
    required: false
    default: '80'
  build-report-dir:
    description: 'Path to build log file'
    required: false
    default: './'
  test-report-dir:
    description: 'Path to test report files'
    required: false
    default: './target/surefire-reports/*.xml'
  coverage-report-dir:
    description: 'Path to coverage report files'
    required: false
    default: './target/site/jacoco/index.html'
  input-dir:
    description: 'Path to source files'
    required: true
    default: './'
  output-dir:
    description: 'Path to output files'
    required: true
    default: './'

runs:
  using: composite
  steps:

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-password }}
        password: ${{ inputs.docker-username }}

    - name: Run QA Assistant
      shell: bash
      run: |
        docker run --rm jacobsonius/qa-assistant:latest \
          "${{ inputs.key }}" \
          "${{ inputs.action-name }}" \
          "${{ inputs.target-value }}" \
          "${{ inputs.build-report-dir }}" \
          "${{ inputs.test-report-dir }}" \
          "${{ inputs.coverage-report-dir }}" \
          "${{ inputs.input-dir }}" \
          "${{ inputs.output-dir }}"